import { call, json, saveImages, client } from "./client.mjs";
const SHOTS = process.argv[2];

const bg = { type: "background", name: "Backdrop", props: { kind: "studio" } };

/* Every content layer is placed by the grid. Nothing uses transform x/y. */
const FILMS = [
  {
    name: "Ship — dev tooling launch",
    theme: "midnight",
    file: "01-midnight-ship",
    scenes: [
      { name: "Cold open", durationInFrames: 70, camera: { move: "push", amount: 0.05 },
        transition: { type: "blur", durationInFrames: 16 },
        layers: [bg,
          { type: "text", name: "Mark", start: 10, layout: { preset: "center" },
            props: { text: "SHIP", fontSize: 24, fontWeight: 500, letterSpacing: 0.5 },
            enter: { preset: "fade", durationInFrames: 28 }, exit: { preset: "fade", durationInFrames: 14 } }]},
      { name: "Claim", durationInFrames: 140, camera: { move: "push", amount: 0.08 },
        transition: { type: "fade", durationInFrames: 18 },
        layers: [bg,
          { type: "component", name: "Headline", layout: { preset: "center" },
            props: { component: "HeroTitle", props: { eyebrow: "Introducing", text: "Deploy on\nevery commit", size: 112,
              caption: "From push to production in ninety seconds. No pipeline to babysit." } },
            enter: { preset: "depthIn", durationInFrames: 32, delay: 4 }, exit: { preset: "blurIn", durationInFrames: 18 } }]},
      { name: "Command", durationInFrames: 165, camera: { move: "push", amount: 0.04 },
        transition: { type: "fade", durationInFrames: 18 },
        layers: [bg,
          { type: "component", name: "Chapter", layout: { preset: "splitLeft" },
            props: { component: "Chapter", props: { number: "01", title: "One command", subtitle: "That is the whole setup.", size: 58 } },
            enter: { preset: "riseFade", durationInFrames: 26 } },
          { type: "component", name: "Term", start: 14, layout: { preset: "splitRight" },
            props: { component: "Terminal", props: { title: "ship", command: "ship deploy --prod", width: 780, fontSize: 21,
              output: "\n  building      done in 4.2s\n  uploading    done in 1.1s\n  live         https://acme.ship.dev" } },
            enter: { preset: "scaleIn", durationInFrames: 24 } }]},
      { name: "Numbers", durationInFrames: 130, camera: { move: "push", amount: 0.04 },
        transition: { type: "fade", durationInFrames: 18 },
        layers: [bg,
          { type: "text", name: "Heading", layout: { preset: "topBand" },
            props: { text: "Boring, on purpose", fontSize: 60, fontWeight: 600, letterSpacing: -0.035 },
            enter: { preset: "riseFade", durationInFrames: 26 } },
          { type: "component", name: "Stats", start: 14, layout: { preset: "middleBand" },
            props: { component: "StatGrid", props: { stats: "90s | push to live\n99.99% | uptime\n0 | config files", size: 90 } } }]},
      { name: "Outro", durationInFrames: 115, camera: { move: "push", amount: 0.03 },
        transition: { type: "none", durationInFrames: 0 },
        layers: [bg,
          { type: "component", name: "Lockup", start: 6, layout: { preset: "center" },
            props: { component: "LogoLockup", props: { wordmark: "Ship", size: 118 } },
            exit: { preset: "fade", durationInFrames: 22 } },
          { type: "text", name: "Tag", start: 36, layout: { preset: "bottomBand" },
            props: { text: "ship.dev", fontSize: 24, letterSpacing: 0.04 },
            enter: { preset: "riseFade", durationInFrames: 24, distance: 14 }, exit: { preset: "fade", durationInFrames: 18 } }]},
    ],
  },
  {
    name: "Aperture — premium brand film",
    theme: "ember",
    file: "02-ember-aperture",
    scenes: [
      { name: "Cold open", durationInFrames: 80, camera: { move: "push", amount: 0.06 },
        transition: { type: "blur", durationInFrames: 18 },
        layers: [bg,
          { type: "text", name: "Mark", start: 14, layout: { preset: "center" },
            props: { text: "APERTURE", fontSize: 22, fontWeight: 500, letterSpacing: 0.55 },
            enter: { preset: "fade", durationInFrames: 32 }, exit: { preset: "fade", durationInFrames: 16 } }]},
      { name: "Object", durationInFrames: 175, camera: { move: "pull", amount: 0.13 },
        transition: { type: "slide", durationInFrames: 18 },
        layers: [bg,
          { type: "component", name: "Card", start: 6, layout: { preset: "centerUpper" },
            props: { component: "ProductCard", props: { title: "Aperture", caption: "Photography, organised", badge: "II", width: 760, height: 450 } },
            enter: { preset: "depthIn", durationInFrames: 38 } },
          { type: "text", name: "Sub", start: 52, layout: { preset: "bottomBand" },
            props: { text: "Every frame you have ever taken, in one place.", fontSize: 30 },
            enter: { preset: "riseFade", durationInFrames: 26, distance: 20 } }]},
      { name: "Craft", durationInFrames: 165, camera: { move: "pan", amount: 0.03 },
        transition: { type: "fade", durationInFrames: 18 },
        layers: [bg,
          { type: "component", name: "Chapter", layout: { preset: "splitLeft" },
            props: { component: "Chapter", props: { number: "01", title: "Built for\nthe long edit", subtitle: "Nothing between you and the image.", size: 60 } },
            enter: { preset: "riseFade", durationInFrames: 28 } },
          { type: "component", name: "Features", start: 16, layout: { preset: "splitRight", align: "left" },
            props: { component: "FeatureList", props: { items: "Raw, everywhere\nNon-destructive by default\nColour that survives export\nWorks offline, always", fontSize: 34 } } }]},
      { name: "Outro", durationInFrames: 120, camera: { move: "push", amount: 0.03 },
        transition: { type: "none", durationInFrames: 0 },
        layers: [bg,
          { type: "component", name: "Lockup", start: 6, layout: { preset: "center" },
            props: { component: "LogoLockup", props: { wordmark: "Aperture", size: 116 } },
            exit: { preset: "fade", durationInFrames: 22 } },
          { type: "text", name: "Tag", start: 38, layout: { preset: "bottomBand" },
            props: { text: "Available now", fontSize: 25, letterSpacing: 0.03 },
            enter: { preset: "riseFade", durationInFrames: 24, distance: 14 }, exit: { preset: "fade", durationInFrames: 18 } }]},
    ],
  },
  {
    name: "Fleet — infrastructure explainer",
    theme: "aurora",
    file: "03-aurora-fleet",
    scenes: [
      { name: "Title", durationInFrames: 100, camera: { move: "push", amount: 0.05 },
        transition: { type: "blur", durationInFrames: 16 },
        layers: [bg,
          { type: "component", name: "Title", layout: { preset: "center" },
            props: { component: "HeroTitle", props: { eyebrow: "How it works", text: "Fleet", size: 128,
              caption: "Container orchestration that fits in your head." } },
            enter: { preset: "depthIn", durationInFrames: 32, delay: 4 }, exit: { preset: "blurIn", durationInFrames: 16 } }]},
      { name: "Pipeline", durationInFrames: 175, camera: { move: "push", amount: 0.04 },
        transition: { type: "fade", durationInFrames: 18 },
        layers: [bg,
          { type: "text", name: "Heading", layout: { preset: "topBand" },
            props: { text: "One path in", fontSize: 58, fontWeight: 600, letterSpacing: -0.035 },
            enter: { preset: "riseFade", durationInFrames: 26 } },
          { type: "component", name: "Flow", start: 12, layout: { preset: "middleBand" },
            props: { component: "DiagramFlow", props: { nodes: "Commit\nBuild\nSchedule\n> Running", direction: "horizontal", nodeWidth: 320, fontSize: 27, gap: 44 } } }]},
      { name: "Layout", durationInFrames: 170, camera: { move: "push", amount: 0.04 },
        transition: { type: "fade", durationInFrames: 18 },
        layers: [bg,
          { type: "component", name: "Chapter", layout: { preset: "splitLeft" },
            props: { component: "Chapter", props: { number: "02", title: "Declared,\nnot scripted", subtitle: "One file describes the whole fleet.", size: 56 } },
            enter: { preset: "riseFade", durationInFrames: 26 } },
          { type: "component", name: "Tree", start: 14, layout: { preset: "splitRight" },
            props: { component: "FileTree", props: { title: "fleet/", tree: "fleet.yaml *\nservices/\n  api/\n  worker/\n  gateway/\nregions/\n  eu-west\n  us-east", fontSize: 26, width: 560 } },
            enter: { preset: "scaleIn", durationInFrames: 24 } },
          { type: "component", name: "Note", start: 108, layout: { preset: "bottomLeft" },
            props: { component: "Callout", props: { label: "RESULT", text: "Same file, every region. No drift.", fontSize: 22, width: 520 } } }]},
      { name: "Outro", durationInFrames: 115, camera: { move: "push", amount: 0.03 },
        transition: { type: "none", durationInFrames: 0 },
        layers: [bg,
          { type: "component", name: "Lockup", start: 6, layout: { preset: "center" },
            props: { component: "LogoLockup", props: { wordmark: "Fleet", size: 116 } },
            exit: { preset: "fade", durationInFrames: 22 } }]},
    ],
  },
  {
    name: "Synth — AI product launch",
    theme: "ultraviolet",
    file: "04-ultraviolet-synth",
    scenes: [
      { name: "Open", durationInFrames: 120, camera: { move: "push", amount: 0.09 },
        transition: { type: "fade", durationInFrames: 18 },
        layers: [bg,
          { type: "component", name: "Title", layout: { preset: "center" },
            props: { component: "HeroTitle", props: { eyebrow: "Introducing", text: "Synth", size: 150,
              caption: "Every voice you need, in every language you ship." } },
            enter: { preset: "depthIn", durationInFrames: 34, delay: 4 }, exit: { preset: "blurIn", durationInFrames: 18 } }]},
      { name: "API", durationInFrames: 170, camera: { move: "push", amount: 0.04 },
        transition: { type: "fade", durationInFrames: 18 },
        layers: [bg,
          { type: "component", name: "Chapter", layout: { preset: "splitLeft" },
            props: { component: "Chapter", props: { number: "01", title: "Three lines", subtitle: "Streaming audio, first byte in 40ms.", size: 58 } },
            enter: { preset: "riseFade", durationInFrames: 26 } },
          { type: "component", name: "Code", start: 14, layout: { preset: "splitRight" },
            props: { component: "CodeBlock", props: { filename: "speak.ts", fontSize: 20, width: 780, lineStagger: 2,
              focusLines: "5-6", focusAt: 84,
              code: "import { synth } from \"@synth/sdk\";\n\nconst audio = await synth.speak({\n  text: \"Your order has shipped.\",\n  voice: \"ava\",\n  language: \"ja\",\n});" } },
            enter: { preset: "scaleIn", durationInFrames: 24 } },
          { type: "component", name: "Note", start: 112, layout: { preset: "bottomLeft" },
            props: { component: "Callout", props: { label: "ANY LANGUAGE", text: "Same voice. Same performance. 140 locales.", fontSize: 22, width: 520 } } }]},
      { name: "Scale", durationInFrames: 140, camera: { move: "push", amount: 0.05 },
        transition: { type: "fade", durationInFrames: 18 },
        layers: [bg,
          { type: "text", name: "Heading", layout: { preset: "topBand" },
            props: { text: "At any scale", fontSize: 62, fontWeight: 600, letterSpacing: -0.035 },
            enter: { preset: "riseFade", durationInFrames: 26 } },
          { type: "component", name: "Stats", start: 14, layout: { preset: "middleBand" },
            props: { component: "StatGrid", props: { stats: "140 | languages\n40ms | first audio\n1B | words a day", size: 92 } } }]},
      { name: "Outro", durationInFrames: 115, camera: { move: "push", amount: 0.03 },
        transition: { type: "none", durationInFrames: 0 },
        layers: [bg,
          { type: "component", name: "Lockup", start: 6, layout: { preset: "center" },
            props: { component: "LogoLockup", props: { wordmark: "Synth", size: 120 } },
            exit: { preset: "fade", durationInFrames: 22 } },
          { type: "text", name: "Tag", start: 36, layout: { preset: "bottomBand" },
            props: { text: "synth.ai", fontSize: 25, letterSpacing: 0.04 },
            enter: { preset: "riseFade", durationInFrames: 24, distance: 14 }, exit: { preset: "fade", durationInFrames: 18 } }]},
    ],
  },
  {
    name: "Ledger — analytics product",
    theme: "arctic",
    file: "05-arctic-ledger",
    scenes: [
      { name: "Title", durationInFrames: 105, camera: { move: "push", amount: 0.05 },
        transition: { type: "blur", durationInFrames: 16 },
        layers: [bg,
          { type: "component", name: "Title", layout: { preset: "center" },
            props: { component: "HeroTitle", props: { eyebrow: "Analytics", text: "Ledger", size: 130,
              caption: "Every number on this page traces back to a row." } },
            enter: { preset: "depthIn", durationInFrames: 32, delay: 4 }, exit: { preset: "blurIn", durationInFrames: 16 } }]},
      { name: "Numbers", durationInFrames: 140, camera: { move: "push", amount: 0.04 },
        transition: { type: "fade", durationInFrames: 18 },
        layers: [bg,
          { type: "text", name: "Heading", layout: { preset: "topBand" },
            props: { text: "Answers, not dashboards", fontSize: 56, fontWeight: 600, letterSpacing: -0.035 },
            enter: { preset: "riseFade", durationInFrames: 26 } },
          { type: "component", name: "Stats", start: 14, layout: { preset: "middleBand" },
            props: { component: "StatGrid", props: { stats: "2.1s | median query\n400B | rows indexed\n1 | source of truth", size: 86 } } }]},
      { name: "Query", durationInFrames: 175, camera: { move: "push", amount: 0.04 },
        transition: { type: "fade", durationInFrames: 18 },
        layers: [bg,
          { type: "component", name: "Chapter", layout: { preset: "splitLeft" },
            props: { component: "Chapter", props: { number: "01", title: "Ask in SQL", subtitle: "No modelling layer to learn first.", size: 58 } },
            enter: { preset: "riseFade", durationInFrames: 26 } },
          { type: "component", name: "Code", start: 14, layout: { preset: "splitRight" },
            props: { component: "CodeBlock", props: { filename: "revenue.sql", language: "text", fontSize: 20, width: 760, lineStagger: 2,
              focusLines: "5-6", focusAt: 88,
              code: "select\n  date_trunc('month', paid_at) as month,\n  sum(amount) / 100 as revenue\nfrom payments\nwhere status = 'succeeded'\ngroup by 1\norder by 1 desc" } },
            enter: { preset: "scaleIn", durationInFrames: 24 } },
          { type: "component", name: "Note", start: 112, layout: { preset: "bottomLeft" },
            props: { component: "Callout", props: { label: "TRACEABLE", text: "Click any figure to see the rows behind it.", fontSize: 22, width: 520 } } }]},
      { name: "Outro", durationInFrames: 115, camera: { move: "push", amount: 0.03 },
        transition: { type: "none", durationInFrames: 0 },
        layers: [bg,
          { type: "component", name: "Lockup", start: 6, layout: { preset: "center" },
            props: { component: "LogoLockup", props: { wordmark: "Ledger", size: 116 } },
            exit: { preset: "fade", durationInFrames: 22 } }]},
    ],
  },
];

const made = [];
for (const film of FILMS) {
  const p = await json("create_project", {
    name: film.file, width: 1920, height: 1080, fps: 30, theme: film.theme,
  });
  await json("build_scenes", { dirName: p.dirName, scenes: film.scenes });
  const tl = await json("timeline", { dirName: p.dirName });
  console.log(`${film.file.padEnd(24)} ${film.theme.padEnd(12)} ${tl.durationInFrames} frames  ${tl.durationTimecode}`);
  made.push({ ...film, dirName: p.dirName });

  const sheet = await call("render_contact_sheet", { dirName: p.dirName, scale: 0.3 });
  await saveImages(sheet, `${SHOTS}/${film.file}`);
}
console.log(JSON.stringify(made.map(m => ({ file: m.file, dirName: m.dirName }))));
await client.close();
